__title__ = "ir_dodecapole_corrections"
__description__ = "Read and write ir_dodecapole_corrections files."
__url__ = "https://github.com/pylhc/ir_dodecapole_corrections"
__version__ = "0.1.0"
__author__ = "pylhc"
__author_email__ = "pylhc@github.com"
__license__ = "MIT"
